### ISSUE TITLE
 Cannot read property 'timeoutProfileCard' of undefined

### ISSUE THREAD

**Issue by Banonevar** [Hambergo/9kmmrbot#32]
Got this on !np command
```
19|| TypeError: Cannot read property 'timeoutProfileCard' of undefined
19||     at /root/scripts//lib/util.js:222:45
19||     at retry (/root/scripts//lib/util.js:109:36)
19||     at Object.getCards (/root/scripts//lib/util.js:222:18)
19||     at processTicksAndRejections (internal/process/task_queues.js:89:5)
19||     at async Command.function [as _function] (/root/scripts//lib/commands/Medals.js:38:16)
```

On !medal little bit different
```
19|| TypeError: Cannot read property 'timeoutProfileCard' of undefined
19||     at /root/scripts//lib/util.js:222:45
19||     at retry (/root/scripts//lib/util.js:109:36)
19||     at Object.getCards (/root/scripts//lib/util.js:222:18)
19||     at processTicksAndRejections (internal/process/task_queues.js:89:5)
19||     at async Command.function [as _function] (/root/scripts//lib/commands/Medals.js:17:15)
```

**Comment by Banonevar** [comment]
Fixed w/o any obviosly reasons..
